name: Godot CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: etc-eos-remote
          preset: ${{ matrix.platform }}
          debugMode: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.0.1
        with:
          name: etc-eos-remote-${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
