name: Godot CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["Linux", "Windows Desktop", "macOS"]
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@f759ed7f8fcb5137cb70873ecf663aa8a1bd998b
        with:
          name: etc-eos-remote
          preset: ${{ matrix.platform }}
          debugMode: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: etc-eos-remote-${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
