name: Godot CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          #- identifier: linux-release
          #  os: ubuntu-latest
          #  export-preset: Linux
          #  debug-mode: false
          #- identifier: linux-debug
          #  os: ubuntu-latest
          #  export-preset: Linux
          #  debug-mode: true
          #- identifier: windows-release
          #  os: ubuntu-latest
          #  export-preset: Windows Desktop
          #  debug-mode: false
          #- identifier: windows-debug
          #  os: ubuntu-latest
          #  export-preset: Windows Desktop
          #  debug-mode: true
          - identifier: macos-release
            os: macos-latest
            export-preset: macOS
            debug-mode: false
            export-filename: etc-eos-remote.dmg
            export-template-location: "/Users/runner/Library/Application Support/Godot/export_templates/4.3.stable"
          #- identifier: macos-debug
          #  os: macos-latest
          #  export-preset: macOS
          #  debug-mode: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          lfs: true
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install --cask godot
      - name: Download and extract export templates
        run: |
          wget https://github.com/godotengine/godot-builds/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
          unzip -a Godot_v4.3-stable_export_templates.tpz
          mkdir -v -p "${{ matrix.export-template-location }}"
          mv ./templates/* "${{ matrix.export-template-location }}"
      - name: Build
        run: |
          mkdir -v -p "${{ github.workspace }}/export"
          godot --headless --export-release "${{ matrix.export-preset }}" "${{ github.workspace }}/export/${{ matrix.export-filename }}"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: etc-eos-remote-${{ matrix.identifier }}
          path: ${{ github.workspace }}/export
